spring.application.name=chat-bot-service
server.port=8080

gemini.api.baseurl=https://generativelanguage.googleapis.com
gemini.api.modelurl=/v1beta/models/gemini-3-flash-preview:generateContent?key={apiKey}
gemini.api.key=${GEMINI_API_KEY}
logging.level.org.springframework.web.reactive.function.client=DEBUG